version: '3' # версия синтаксиса
services:
  express-app:
    build: .
    ports:
      - '3000:3000'
    depends_on:
     - angular-app
    develop:
      watch:
        - action: rebuild
          path: ./package.json
        - action: sync
          path: .
          target: /app
  angular-app:
    build: ./ui
    ports:
      - '4201:4200'

